GET http://localhost:8080/code/sms?mobile=13012345678
Content-Type: application/x-www-form-urlencoded
deviceId: 123

###

POST http://localhost:8080/authentication/mobile?mobile=13012345678&smsCode=176162
Authorization: Basic c2VlZDpzZWVkc2VjcmV0
Content-Type: application/x-www-form-urlencoded
deviceId: 123

###
