spring:
  session:
    store-type: none
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      url: jdbc:mysql://127.0.0.1:3306/seed_security?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
      username: root
      password: 123456
logging:
  level:
    com.fengxuechao.seed.security.example: debug

seed:
  security:
    browser:
      signInResponseType: REDIRECT
#      singInSuccessUrl: /index.html